apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cert
  namespace: lldap
spec:
  dnsNames:
    - lldap.macnichol.us
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: cloudflare-cluster-issuer
  secretName: cert
  usages:
    - digital signature
    - key encipherment
