apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cert-macnichol
  namespace: gateway
spec:
  dnsNames:
    - "*.macnichol.us"
    - macnichol.us
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: cloudflare-cluster-issuer
  secretName: cert-macnichol
  usages:
    - digital signature
    - key encipherment
