apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - cert-macnichol.yaml
  - gateway-class.yaml
  - ns.yaml
  - gw-external.yaml
  - gw-internal.yaml
  - gw-tls-passthrough.yaml
