apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: monitoring
  namespace: argocd
  labels:
    dev.macnichol: monitoring
spec:
  generators:
    - git:
        repoURL: https://github.com/vehagn/homelab
        revision: HEAD
        directories:
          - path: k8s/infra/monitoring/*
  template:
    metadata:
      name: '{{ path.basename }}'
      labels:
        dev.macnichol: controllers
    spec:
      project: monitoring
      source:
        plugin:
          name: kustomize-build-with-helm
        repoURL: https://github.com/vehagn/homelab
        targetRevision: HEAD
        path: '{{ path }}'
      destination:
        name: in-cluster
        namespace: argocd
      syncPolicy:
        automated:
          selfHeal: true
          prune: true
        syncOptions:
          - ApplyOutOfSyncOnly=true
          - ServerSideApply=true
